# Generated by Django 4.2.5 on 2023-12-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadwayreport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_official',
            field=models.BooleanField(default=False),
        ),
    ]
